core/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('medicalcenter.urls', 'medicalcenter'), namespace='mc')),
]

medicalcenter/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    path(
        route='geo/',
        view=TemplateView.as_view(template_name="geo.html"),
        name='index',
    ),
    path(
        route='calculate_index/',
        view=views.calculate_index,
        name='calculate_index',
    ),
    path(
        route='result_list/',
        view=views.ResultListView.as_view(),
        name='result_list',
    ),
]

medicalcenter/models.py
from django.db import models


class Result(models.Model):
    radius = models.CharField(max_length=20)
    initial_lat = models.FloatField()
    initial_lon = models.FloatField()
    index = models.IntegerField()


class Coordinate(models.Model):
    lat = models.FloatField()
    lon = models.FloatField()
    result = models.ForeignKey('Result', on_delete=models.CASCADE)

    def __str__(self):
        return '{}, {}'.format(self.lat, self.lon)

medicalcenter/views.py
# Django
from django.views.generic.list import ListView
from django.shortcuts import render
# Apps
from .models import Result, Coordinate
# Python
import requests
# 3rd party
from geopy.distance import geodesic


def calculate_index(request):
    """
    Calculate the minimun index for a point and a radius
    """
    radius = str(int(request.POST.get('radius', 0))*1000)
    lat = request.POST.get('lat', 0)
    lon = request.POST.get('lon', 0)
    if lat and lon and radius:
        index, points = get_hospitals(lat, lon, radius)
        if index:
            result = Result(
                radius=radius,
                initial_lat=lat,
                initial_lon=lon,
                index=index,
            )
            result.save()
            if points:
                for point in points:
                    coordinate = Coordinate(
                        lat=point[0],
                        lon=point[1],
                        result=result
                    )
                    coordinate.save()
        response = render(request, 'result.html', {'result': index})
    else:
        msg = 'error :('
        response = render(request, 'error.html', {'msg': msg})
    return response


def get_hospitals(latitude, longitude, radius):

    point_ini = (latitude, longitude)
    location = "{},{}".format(latitude, longitude)
    api_endpoint = "https://maps.googleapis.com/maps/api/place/nearbysearch/json?location="+location+"&radius="+radius+"&type=hospital&key=AIzaSyD2axpiyRvdl1CtD9CNpmIPfsJkHIE6ycc"
    print (api_endpoint)
    response = requests.get(api_endpoint)
    resp = response.json()
    distances = []
    points = []
    for place in resp['results']:
        lat = place['geometry']['location']['lat']
        lng = place['geometry']['location']['lng']
        point = (lat, lng)
        points.append(point)
        distances.append(int(get_distance(point_ini, point)))
    index = 0
    for i in distances:
        partial_index = 0
        for j in distances:
            partial_index += (abs(i-j))
        if (partial_index < index) or (index == 0):
            index = partial_index
    return index, points


def get_distance(point_a, point_b):
    """
    Calculate the distance between 2 geographic points
    eg:
        pointa_a: (41.49008, -71.312796)
        pointa_b: (41.499498, -81.695391)
    """
    return geodesic(point_a, point_b).km


class ResultListView(ListView):
    model = Result
    template_name = 'result_list.html'
    context_object_name = 'result_list'

medicalcenter/templates/error.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        Error: {{ msg }}
    </body>
</html>

medicalcenter/templates/geo.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <form class="" id="form" action="{% url 'mc:calculate_index' %}" method="post" enctype="multipart/form-data" style="display: grid;grid-template-columns: 173px;">
            {% csrf_token %}
            <div class="">
                <label for="">Radius (KM)</label>
                <input type="number" name="radius" value="0" min="0" reqired>
            </div>
            <div class="">
                <label for="">Latitude</label>
                <input type="text" name="lat" value="" reqired>
            </div>
            <div class="">
                <label for="">Longitude</label>
                <input type="text" name="lon" value="" reqired>
            </div>
            <input type="submit" name="" value="Submit">
        </form>
        <a href="{% url 'mc:result_list' %}">Show results history</a>

    </body>
</html>

medicalcenter/templates/result.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <div class="">
            <label for="">Result:</label>
            <div class="">
                {{ result }}
            </div>
            <a href="{% url 'mc:result_list' %}">Show results history</a>
        </div>
    </body>
</html>

medicalcenter/templates/result_list.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        {% for result in result_list %}
        <p style="color: red"> ----------------- SEARCH ----------------------</p>
            <div class="">
                Radio {{result.radius}} meters
            </div>
            <div class="">
                Latitude {{result.initial_lat}}
            </div>
            <div class="">
                Longitude {{result.initial_lon}}
            </div>
            <div class="">
                Index {{result.index}}
            </div>
            <br>
            POINTS
            <div class="" style=" height:50px; overflow-y:scroll; border: 1px solid #bababa">
                {% for coordinate in result.coordinate_set.all %}
                <p>
                    {{coordinate.lat}}, {{coordinate.lon}}
                </p>
                {% endfor %}
            </div>
            
        {% endfor %}
    </body>
</html>